>>> side1 = float(input("Enter the first side: "))
Enter the first side: 5
>>> side2 = float(input("Enter the second side: "))
Enter the second side: 5
>>> side3 = float(input("Enter the third side: "))
Enter the third side: 5
>>> if side1 == side2 == side3:
...      print("The triangle is equilateral.")
...
The triangle is equilateral.
>>> else:
  File "<python-input-4>", line 1
    else:
    ^^^^
SyntaxError: invalid syntax
>>>
